### ISSUE TITLE
Error installing filebeat

### ISSUE THREAD

**Issue by rodrigdav** [strootman/ansible-beats#3]
When I install file beat I get the following error.  

"The conditional check 'beat.geoip' failed. The error was: error while evaluating conditional (beat.geoip):

I am not entirely sure what is going on as I think everything is configured correctly.

**Comment by strootman** [comment]
@rodrigdav, my apologies for the delay.

I think this is a documentation issue.

If you did not install the role from Ansible Galaxy, then the dependent [cyverse.geoip](https://galaxy.ansible.com/cyverse/beats/) role was not installed. You will have to do so manually.

However, I just pushed in another set of changes to update this role for `v5.x`, which includes removing that dependency. Read the commit message on 141142b.

I'll leave this open until COB Friday, but I think the issue is resolved.

**Comment by rodrigdav** [comment]
Thank you.  I will try the new version.
